"""Typed, framework-neutral application configuration schemas."""

from legal_agentic_rag.configuration.application import ApplicationConfig
from legal_agentic_rag.configuration.artifacts import ArtifactConfig
from legal_agentic_rag.configuration.build_validation import BuildValidationConfig
from legal_agentic_rag.configuration.competition import (
    CompetitionConfig,
    OFFICIAL_CORPUS_DATASET_NAME,
    OFFICIAL_QA_DATASET_NAME,
)
from legal_agentic_rag.configuration.evaluation import (
    EvaluationCandidateConfig,
    EvaluationComparisonConfig,
    EvaluationConfig,
    EvaluationObjectiveConfig,
)
from legal_agentic_rag.configuration.observability import LoggingConfig
from legal_agentic_rag.configuration.m54_production import (
    M54_PARAMETER_LIMIT,
    M54_PRODUCTION_SCHEMA_VERSION,
    M54_TOTAL_ACTIVE_MODEL_PARAMETERS,
    build_m54_embedding_config,
    build_m54_online_config,
)
from legal_agentic_rag.configuration.m55_production import (
    M55_EXPECTED_RECORD_COUNT,
    M55_LOOKUP_FILENAME,
    M55_LOOKUP_SHA256,
    M55_MAX_ARTICLES,
    M55_PARAMETER_LIMIT,
    M55_PRODUCTION_SCHEMA_VERSION,
    M55_RETRIEVAL_TIMEOUT_SECONDS,
    M55_STRUCTURAL_FALLBACK_MAX_EVIDENCE,
    build_m55_embedding_config,
    build_m55_online_config,
)
from legal_agentic_rag.configuration.serving import ServingConfig
from legal_agentic_rag.configuration.offline import (
    BM25IndexConfig,
    ChunkingConfig,
    EmbeddingConfig,
    GraphIndexConfig,
    HtmlCleaningConfig,
    IndexBuildConfig,
    LegalStructureParserConfig,
    OfflineConfig,
    VectorIndexConfig,
)
from legal_agentic_rag.configuration.online import (
    AgentConfig,
    ArticleAnswerConfig,
    BM25RuntimeConfig,
    ClaimVerificationConfig,
    ContextGradingConfig,
    EvidenceSelectionConfig,
    GenerationConfig,
    OnlineConfig,
    QueryUnderstandingConfig,
    RerankerConfig,
    RetrievalArtifactMode,
    RetrievalConfig,
    SemanticVerificationConfig,
    StartupValidationConfig,
    VectorRuntimeConfig,
)

__all__ = [
    "AgentConfig",
    "ArticleAnswerConfig",
    "BM25RuntimeConfig",
    "ApplicationConfig",
    "ArtifactConfig",
    "BM25IndexConfig",
    "BuildValidationConfig",
    "ClaimVerificationConfig",
    "CompetitionConfig",
    "ChunkingConfig",
    "ContextGradingConfig",
    "EvidenceSelectionConfig",
    "EmbeddingConfig",
    "EvaluationConfig",
    "EvaluationCandidateConfig",
    "EvaluationComparisonConfig",
    "EvaluationObjectiveConfig",
    "GenerationConfig",
    "GraphIndexConfig",
    "HtmlCleaningConfig",
    "IndexBuildConfig",
    "LegalStructureParserConfig",
    "LoggingConfig",
    "M54_PARAMETER_LIMIT",
    "M54_PRODUCTION_SCHEMA_VERSION",
    "M54_TOTAL_ACTIVE_MODEL_PARAMETERS",
    "build_m54_embedding_config",
    "build_m54_online_config",
    "M55_EXPECTED_RECORD_COUNT",
    "M55_LOOKUP_FILENAME",
    "M55_LOOKUP_SHA256",
    "M55_MAX_ARTICLES",
    "M55_PARAMETER_LIMIT",
    "M55_PRODUCTION_SCHEMA_VERSION",
    "M55_RETRIEVAL_TIMEOUT_SECONDS",
    "M55_STRUCTURAL_FALLBACK_MAX_EVIDENCE",
    "build_m55_embedding_config",
    "build_m55_online_config",
    "OfflineConfig",
    "OnlineConfig",
    "OFFICIAL_CORPUS_DATASET_NAME",
    "OFFICIAL_QA_DATASET_NAME",
    "QueryUnderstandingConfig",
    "RerankerConfig",
    "SemanticVerificationConfig",
    "ServingConfig",
    "StartupValidationConfig",
    "RetrievalArtifactMode",
    "RetrievalConfig",
    "VectorIndexConfig",
    "VectorRuntimeConfig",
]
